import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Serwist at build time — never lint.
    "public/sw.js",
    "public/swe-worker-*.js",
    // Standalone PPT build scripts (CommonJS Node tooling) — not app code.
    "slides/**",
  ]),
]);

export default eslintConfig;
