include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.drift.dart"

linter:
  rules:
    - avoid_print: true
    - prefer_single_quotes: true
