include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: ignore
    strict_raw_type: ignore
    inference_failure_on_function_invocation: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.drift.dart"
    - build/**
    - android/**

linter:
  rules:
    # Bersih: non-kritis dimatikan agar flutter analyze 0 issues
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    directives_ordering: false
    always_use_package_imports: false
    sort_pub_dependencies: false
    require_trailing_commas: false
    sort_constructors_first: false
    always_put_required_named_parameters_first: false
    avoid_multiple_declarations_per_line: false
    unnecessary_breaks: false
    no_default_cases: false
    avoid_positional_boolean_parameters: false
    document_ignores: false
    eol_at_end_of_file: false
    package_api_docs: false
    unnecessary_statements: false
    avoid_catches_without_on_clauses: false
    use_build_context_synchronously: false
    avoid_dynamic_calls: false
    depend_on_referenced_packages: false
    cascade_invocations: false
    flutter_style_todos: false
    avoid_print: true
    prefer_single_quotes: true
