-- Migration 001 already creates user_role as ('admin', 'qc', 'produksi') directly,
-- so this migration is a no-op. It exists solely for documentation/history purposes.
-- In a fresh install, the enum values are already correct.
